services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"  # This exposes MySQL to your host machine
    environment:
      MYSQL_USER: web
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: texty
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: